# Generated by Django 2.2.4 on 2019-08-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20190814_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades'},
        ),
    ]
